version: '3'

services:

  api:
    build: .
    image: solidelections/api
    restart: always
    ports:
      - 80:8000
    environment:
      - DEBUG=${DEBUG}
      - PG_HOST=${PG_HOST}
      - PG_DBNAME=${PG_DBNAME}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
      - SPARQL_URL=${SPARQL_URL}

  db:
    image: postgres:alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
    volumes:
      - ./pgdata:/var/lib/postgresql/data