version: '3.1'

services:

  api:
    build: .
    restart: always
    ports:
      - 80:8000
    volumes:
      - ./src:/usr/src/app
    environment:
      - DEBUG=${DEBUG}
      - PG_HOST=${PG_HOST}
      - PG_DBNAME=${PG_DBNAME}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}

  db:
    image: postgres:alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
